version: "3.8"

services:
  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=xmtest
      - POSTGRES_PASSWORD=hello
    networks:
      - assessment
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  testdb:
    image: postgres:14
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=xmtest
      - POSTGRES_PASSWORD=hello
    networks:
      - assessment
    volumes:
      - testdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  dbdata:
  testdata:

networks:
  assessment: