version: "3.8"

services:
  db:
    image: postgres:14
    container_name: "database"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=xmtest
      - POSTGRES_PASSWORD=hello
    networks:
      - assessment
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:

networks:
  assessment: